services:
  - type: web
    name: expense-tracker
    env: java
    plan: free
    buildCommand: chmod +x ./mvnw && ./mvnw clean package -DskipTests
    startCommand: java -jar target/expense-tracker-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_VERSION
        value: 21
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: SPRING_JPA_SHOW_SQL
        value: false
      - key: SPRING_JPA_FORMAT_SQL
        value: false
      - key: SPRING_THYMELEAF_CACHE
        value: true
      - key: RECAPTCHA_SITE_KEY
        sync: false
      - key: RECAPTCHA_SECRET_KEY
        sync: false
      - key: OPEN_API_KEY
        sync: false
      - key: OPENROUTER_API_BASE
        value: https://openrouter.ai/api/v1
